# Generated by Django 5.1 on 2024-08-30 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacao', models.DateField(auto_now_add=True)),
                ('atualizacao', models.DateField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=255)),
                ('registro', models.IntegerField(max_length=8)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professores',
            },
        ),
    ]
