# Generated by Django 5.1 on 2024-08-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='registro',
            field=models.IntegerField(unique=True),
        ),
    ]
