# Generated by Django 5.1 on 2024-08-31 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_professor_registro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['id'], 'verbose_name': 'avaliacão', 'verbose_name_plural': 'avaliações'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['id'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['id'], 'verbose_name': 'professor', 'verbose_name_plural': 'professores'},
        ),
    ]
